### ISSUE TITLE
multiple invocations of same alias

### ISSUE THREAD

**Issue by dwntwnbrown** [ECSTeam/pcf#1]
Currently creates a new target entry rather than update the existing one.
Should warn when aliasing an org or space that does not exists

**Comment by wrast** [comment]
There's 2 issues described here.

1. Confirmed the duplicate alias behavior. Probably have a warning displayed and just go ahead with an overwrite. This isn't devastating behavior so don't feel like prompting the user before overwriting is necessary.

2. Script is at the mercy of the `cf login` command when targeting org/space. I don't know that there's much that can be done to warn the user beyond what `cf` displays.

I'll fix the first issue for now.

**Comment by wrast** [comment]
Changes made to overwrite an existing alias.
